server:
  port: 8383
spring:
  application:
    name: gateway-service
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
